- name: Write kv secrets
  shell: |
    echo -n '{{ item.1 }}' | vault kv put secret/{{ item.0.name }} -
  args:
    executable: /bin/bash
  with_subelements:
    - "{{ secrets }}"
    - payload
  tags:
    - vault
    - kv_secrets